# Generated by Django 2.1.3 on 2018-11-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0003_scratch_scratch_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinbag',
            name='scratch_type',
        ),
        migrations.AddField(
            model_name='coinbag',
            name='scratch_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lotto.ScratchGroup'),
            preserve_default=False,
        ),
    ]
