# Generated by Django 2.1.3 on 2018-11-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0004_auto_20181124_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scratchtype',
            old_name='amounts',
            new_name='awards',
        ),
    ]
