# Generated by Django 2.1.3 on 2018-11-24 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0005_auto_20181124_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
